name: hafc-bouwen
on:
  push:
    tags: ['*']
jobs:
  bouwen:
    runs-on: ubuntu-22.04
    environment: prod
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: "checkout doen"
        uses: actions/checkout@v3
      - name: npm meuk installeren
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: "wie ben ik"
        run: "npm -v && node -v && lsb_release -a"
      - name: "npm dependencies ophalen"
        run: "npm install"
      - name: SSR build
        run: "npm run build:ssr"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: hafc-ssr
        run: |
          IMAGE_TAG_SUFFIX="$(date -u +"%Y_%m_%d")-$(git rev-parse --short "$GITHUB_SHA")"
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:amd64-${IMAGE_TAG_SUFFIX} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:amd64-${IMAGE_TAG_SUFFIX}
          docker buildx build --platform linux/arm64 --push \
           -t $ECR_REGISTRY/$ECR_REPOSITORY:arm64-${IMAGE_TAG_SUFFIX} -f ./Dockerfile .